# Generated by Django 5.0.4 on 2024-04-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientid', models.AutoField(db_column='PatientID', primary_key=True, serialize=False)),
                ('fileserial', models.CharField(blank=True, db_column='FileSerial', max_length=150, null=True)),
                ('fullname', models.CharField(blank=True, db_column='FullName', max_length=150, null=True)),
                ('birthdate', models.DateField(blank=True, db_column='BirthDate', null=True)),
                ('gender', models.BooleanField(blank=True, db_column='Gender', null=True)),
                ('mobile', models.CharField(blank=True, db_column='Mobile', max_length=50, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=1000, null=True)),
                ('city', models.IntegerField(blank=True, db_column='City', null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=150, null=True)),
                ('createddate', models.DateField(blank=True, db_column='CreatedDate', null=True)),
                ('createdby', models.IntegerField(blank=True, db_column='CreatedBy', null=True)),
                ('latestupdate', models.DateField(blank=True, db_column='LatestUpdate', null=True)),
                ('updatedby', models.IntegerField(blank=True, db_column='UpdatedBy', null=True)),
            ],
        ),
    ]
