# Generated by Django 5.0.4 on 2024-04-26 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVisits',
            fields=[
                ('visitid', models.AutoField(db_column='VisitID', primary_key=True, serialize=False)),
                ('visitdate', models.DateField(blank=True, db_column='VisitDate', null=True)),
                ('reasonforvisit', models.TextField(blank=True, db_column='ReasonForVisit', null=True)),
                ('diagnosis', models.TextField(blank=True, db_column='Diagnosis', null=True)),
                ('treatment', models.TextField(blank=True, db_column='Treatment', null=True)),
                ('followup', models.TextField(blank=True, db_column='FollowUp', null=True)),
                ('evaluationeegree', models.CharField(blank=True, db_column='EvaluationDegree', max_length=1, null=True)),
                ('createdate', models.DateField(blank=True, db_column='CreateDate', null=True)),
                ('doctorid', models.ForeignKey(blank=True, db_column='DoctorID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='doctors.doctor')),
                ('patient', models.ForeignKey(blank=True, db_column='PatientID', null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
