# Generated by Django 5.0.4 on 2024-04-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patientvisits'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.ImageField(null=True, upload_to='patients/photos/%y/%m/%d'),
        ),
    ]
