# Generated by Django 5.0.4 on 2024-04-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-fullname'], 'verbose_name': 'Patients List'},
        ),
        migrations.AddField(
            model_name='patient',
            name='comingsource',
            field=models.CharField(blank=True, choices=[('Facebook', 'Facebook'), ('Newspaper', 'Newspaper'), ('Friend', 'Friend')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthdate',
            field=models.DateField(db_column='BirthDate', null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fileserial',
            field=models.CharField(db_column='FileSerial', max_length=150, null=True, verbose_name='File Number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fullname',
            field=models.CharField(db_column='FullName', default='Patient Name', max_length=150, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.BooleanField(db_column='Gender', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(default='photos/patient.jpg', null=True, upload_to='patients/photos/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile',
            field=models.CharField(db_column='Mobile', max_length=50, null=True),
        ),
    ]
