# Generated by Django 5.0.4 on 2024-04-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_options_patient_comingsource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='fileserial',
            field=models.CharField(db_column='FileSerial', error_messages='The Patient file number is requiered', max_length=150, null=True, verbose_name='File Number'),
        ),
    ]
