# Generated by Django 5.0.4 on 2024-04-29 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patient_fileserial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientvisits',
            old_name='patient',
            new_name='patientid',
        ),
    ]
