# Generated by Django 5.0.4 on 2024-04-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_rename_patient_patientvisits_patientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvisits',
            name='visitdate',
            field=models.DateTimeField(blank=True, db_column='VisitDate', null=True),
        ),
    ]
