# Generated by Django 5.0.4 on 2024-04-30 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_patientvisits_visitdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientvisits',
            name='followup',
        ),
    ]
