# Generated by Django 5.0.4 on 2024-04-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_remove_patientvisits_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisits',
            name='followup',
            field=models.BooleanField(blank=True, db_column='FollowUp', null=True),
        ),
    ]
