# Generated by Django 5.0.4 on 2024-05-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_patientvisits_followup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-fullname'], 'verbose_name': 'Patients'},
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(blank=True, db_column='Age', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='remarks',
            field=models.CharField(blank=True, db_column='Remarks', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='reservedBy',
            field=models.CharField(blank=True, db_column='ReservedBy', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, db_column='City', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fullname',
            field=models.CharField(db_column='FullName', max_length=150, null=True, verbose_name='Patient Name'),
        ),
    ]
