# Generated by Django 5.0.4 on 2024-05-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_patient_arrivedon_patient_sufferedcase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='createddate',
        ),
        migrations.AddField(
            model_name='patient',
            name='ExpectedDate',
            field=models.DateField(blank=True, db_column='ExpectedDate', null=True),
        ),
    ]
