# Generated by Django 5.0.4 on 2024-05-06 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_remove_patient_createddate_patient_expecteddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='ExpectedDate',
            new_name='expectedDate',
        ),
    ]
