# Generated by Django 5.0.4 on 2024-04-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('DoctorID', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=255)),
                ('Mobile', models.CharField(max_length=155, null=True)),
                ('SpecialtyID', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(null=True, upload_to='doctors/photos/%y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('SpecialtyID', models.AutoField(primary_key=True, serialize=False)),
                ('SpecialtyNam', models.CharField(max_length=255)),
            ],
        ),
    ]
