# Generated by Django 5.0.4 on 2024-04-27 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_specialtyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='SpecialtyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctors.specialties'),
        ),
    ]
