# Generated by Django 5.0.4 on 2024-04-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctor_specialtyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='photos/doctor.jpg', null=True, upload_to='doctors/photos/%y/%m/%d'),
        ),
    ]
