# Generated by Django 5.0.4 on 2024-05-06 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_alter_doctor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='DoctorID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Dcotor ID'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='FullName',
            field=models.CharField(max_length=255, verbose_name='Doctor Name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='SpecialtyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctors.specialties', verbose_name='Speciality Name'),
        ),
    ]
